/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'isBreaking' : IDL.Bool,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getArticles' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getTrendingTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'isBreaking' : IDL.Bool,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getArticles' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getTrendingTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };